name: Generate Workflow
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  generate-workflow:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Install Dhall
        uses: dhall-lang/setup-dhall@v4
        with:
          github_token: ${{ github.token }}
      - name: Convert Dhall to YAML
        run: dhall-to-yaml --file workflow.dhall > .github/workflows/deploy.yml

      - name: Commit generated workflow
        run: | 
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .github/workflows/deploy.yml
            git commit -m "Generate workflow from Dhall" || echo "No changes"
            git push
